# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
