# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0002_countries_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
