# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0003_cities_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='cities',
            name='local_name',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
