# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_user_blk_flg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_passwd',
            new_name='user_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=200),
        ),
    ]
