# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20190213_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('user_name', 'user_password')]),
        ),
    ]
