# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-14 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20190213_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
