# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('pick_up', models.CharField(max_length=200, null=True)),
                ('drop_off', models.CharField(max_length=200, null=True)),
                ('location_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Countries.Locations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User')),
            ],
        ),
    ]
