# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0008_auto_20190214_1452'),
        ('Countries', '0006_auto_20190214_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Rental',
            fields=[
                ('car_rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_rental_name', models.CharField(max_length=45)),
                ('location_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Countries.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('pick_up', models.CharField(max_length=200, null=True)),
                ('drop_off', models.CharField(max_length=200, null=True)),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Rental.Car_Rental')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User')),
            ],
        ),
    ]
