# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
        ('Car_Rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_rental',
            name='location_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Countries.locations'),
            preserve_default=False,
        ),
    ]
