# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Car_Rental', '0002_car_reservation_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_reservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
