# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Rental', '0016_auto_20190214_1035'),
        ('Car_Rental', '0010_auto_20190213_2334'),
    ]

    operations = [
    ]
