# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Rental', '0039_auto_20190215_1236'),
        ('Car_Rental', '0020_auto_20190214_1642'),
    ]

    operations = [
    ]
