# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservationrequest',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelreservationrequest',
            name='to_date',
            field=models.DateField(),
        ),
    ]
