# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Different',
            fields=[
                ('diff_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
