# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='Admin',
        ),
    ]
